### ISSUE TITLE
[Feature] Webpage with Live Data as usable Overlay in Stream

### ISSUE THREAD

**Issue by edhor1608** [jakoblorz/autofone#9]
The latency of the website from game data to display on the web is surprisingly short, but still unsuitable for live / real-time insertions. Therefore the idea that the tool directly uses its own web server and hosts the data locally as a website (UI for this would still have to be worked out). The streamer could then use this in the stream as an overlay.

**Comment by edhor1608** [comment]
Workaround: Send Data to two seperate URLs: local + web, maybe local hardcoded + web as property in Terminal

**Comment by jakoblorz** [comment]
Local will not be hardcoded, but with #11 there will be support for 2 protocol exposures:
- WebSocket for live timings
- HTTP+POST for general packages
